name: AdoptopenJDK Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
      jdk_version:
        description: 'jdk version'
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: adoptopenjdk/${{ github.event.inputs.tag_name }}
        push: true
        tags: an0nymous/openjdk${{ github.event.inputs.jdk_version }}-openj9:${{ github.event.inputs.tag_name }}
