name: AdoptopenJDK Docker Image CI

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'dockerfile path'
        required: true
      push_tags:
        description: 'push tags name'
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: adoptopenjdk/${{ github.event.inputs.filename }}
        push: true
        tags: an0nymous/${{ github.event.inputs.push_tags }}
