name: Docker Image CI1

on: workflow_dispatch


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build . --file /adoptopenjdk/jdk8u302-b08_openj9-0.27.1-slim --tag an0nymous/openjdk8-openj9:jdk8u302-b08_openj9-0.27.1-slim
      with:
        registry: an0nymous/openjdk8-openj9:jdk8u302-b08_openj9-0.27.1-slim
        username: 1
        password: 4
