name: AdoptopenJDK Docker Image CI

on: workflow_dispatch


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          registry: an0nymous/openjdk8-openj9:jdk8u302-b08_openj9-0.27.0-slim
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: adoptopenjdk/jdk8u302-b08_openj9-0.27.0-slim
        push: true
        tags: an0nymous/openjdk8-openj9:jdk8u302-b08_openj9-0.27.0-slim
